<?php
// PHP Script generated by HTML2PHP Converter v1.0.0
// Developed by Naresh Manandhar (Crystal Softworks: www.cswnepal.com)
// E-mail: nareshmdr@yahoo.com URL: www.nareshmdr.com.np

echo "\n";
echo "<div class=\"container\">\n";
echo "      <div class=\"row\">\n";
echo "        <div class=\"col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad\" >\n";
echo "          <div class=\"panel panel-info\">\n";
echo "            <div class=\"panel-heading\">\n";
echo "              <h3 class=\"panel-title\">Thay đổi thông tin</h3>\n";
echo "            </div>\n";
echo "            <div class=\"panel-body\">\n";
echo "              <div class=\"row\">\n";
echo "            \n";
echo "                <div class=\" col-md-9 col-lg-9 \"> \n";
echo "                  <form method='POST' action='#'>\n";
echo "                  <table class=\"table table-user-information\">\n";
echo "                    <tbody>\n";
echo "                      <tr>\n";
echo "                        <td>Họ và tên</td>\n";
echo "                        <td><input type='text' name='name' size='20'></td>\n";
echo "                      </tr>\n";
echo "                      <tr>\n";
echo "                        <td>Ngày sinh</td>\n";
echo "                        <td><input type='text' name='sn'  size='20'></td>\n";
echo "                      </tr>\n";
echo "                      <tr>\n";
echo "                        <td>Số điện thoại</td>\n";
echo "                        <td><input type='text' name='sdt' size='20'></td>\n";
echo "                      </tr>\n";
echo "                      <tr>\n";
echo "                        <td>Pass:</td>\n";
echo "                        <td><input type='password' name='pass' size='20'></td>\n";
echo "                      </tr>\n";
echo "                   \n";
echo "                    \n";
echo "                    <tr>\n";
echo "                        <td>Email</td>\n";
echo "                        <td><input type='text' name='email' size='20'></td>\n";
echo "                      </tr>\n";
echo "                        \n";
echo "                     \n";
echo "                    </tbody>\n";

echo "                <td><a href=\"home.php\" class=\"btn btn-warning\"><i class=\"fa fa-angle-left\"></i>  Về trang chủ</a><td>\n";
echo "\t\t\t\t\t\t\t<p><input type='submit' class=\"btn btn-primary\" name='btn_submit' value='Thay đổi thông tin'></p>\n";

echo "                  </table>\n";
echo "                  \n";


echo "        </form>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "                 \n";
echo "            \n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "";
?>